### ISSUE TITLE
Assertion error in framework.py

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#14]
After building the IGTD image from scratch, I get an assertion error. I am not sure if this is a problem within framework.py or IGTD.

Command:
`singularity run --nv -B /homes/wilke/IMPROVE/HPO/experiments/HPO2404:/candle_data_dir /homes/wilke/IMPROVE/Singularity/build//IGTD.sif train.sh 0 /candle_data_dir --model_outdir /candle_data_dir/outputs/IGTD/train/gCSI --train_ml_data_dir /candle_data_dir/outputs/IGTD/preprocess/gCSI --test_ml_data_dir /candle_data_dir/outputs/IGTD/preprocess/gCSI --val_ml_data_dir /candle_data_dir/outputs/IGTD/preprocess/gCSI --epochs 1`

Output:
```
2024-04-19 12:06:22.900317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30575 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1a:00.0, compute capability: 7.0)
Traceback (most recent call last):
  File "/usr/local/IGTD//IGTD_train_improve.py", line 243, in <module>
    main()
  File "/usr/local/IGTD//IGTD_train_improve.py", line 238, in main
    val_scores = run(params)
  File "/usr/local/IGTD//IGTD_train_improve.py", line 214, in run
    outdir=params["model_outdir"]
  File "/usr/local/IMPROVE/improve/framework.py", line 502, in store_predictions_df
    assert np.array_equal(v1, v2), ""\
AssertionError: Y data vector from the loaded metadata is not equal to the true vector:
Y data vector from loaded metadata:  [0.9058 0.9771 0.7761 0.9517 0.5397 0.7037 0.8988 0.5201 0.4313 0.4263]
Y data vector of true target values: [0.6188 0.9285 0.9028 0.233  0.6991 0.3291 0.8823 0.6147 0.8348 0.9368]

Command exited with non-zero status 1
```

**Comment by wilke** [comment]
@adpartin is the related to PR #10 ?

**Comment by wilke** [comment]
Seems to be an issue with framework.py, I get the same error with Paccmann.

**Comment by adpartin** [comment]
@wilke It is. But it should work now. Please check.

**Comment by wilke** [comment]
This is a tentative yes. It seems to work with Paccmann.

**Comment by adpartin** [comment]
@wilke should we close?

**Comment by wilke** [comment]
Closing for now.
