### ISSUE TITLE
Bug in CLI

### ISSUE THREAD

**Issue by priyanka9991** [JDACS4C-IMPROVE/IMPROVE#15]
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    cli.set_command_line_options(options=additional_definitions)
  File "/IMPROVE/improve/CSA/CLI.py", line 75, in set_command_line_options
    self.logger.debug("Adding %s to Command Line Options" , options[k]['name'])

**Comment by priyanka9991** [comment]
I was able to fix this. Change commited.
